Update azure-pipelines-1.yml

diff --git a/azure-pipelines-1.yml b/azure-pipelines-1.yml
--- a/azure-pipelines-1.yml
+++ b/azure-pipelines-1.yml
@@ -30,7 +30,7 @@ jobs:
     - script: |
         ls -la
         pwd
-        cd $(Build.SourcesDirectory)/azure-1
+        cd $(Build.SourcesDirectory)/azure-1 || { echo "Error: Unable to change directory."; exit 1; }
         pwd
         terraform init
       displayName: 'Terraform Init'
@@ -68,11 +68,11 @@ jobs:
     vmImage: 'ubuntu-latest'
   steps:
     - script: |
-        cd $(Build.SourcesDirectory)/azure-1
+        cd $(Build.SourcesDirectory)/azure-1 || { echo "Error: Unable to change directory."; exit 1; }
         pwd
         ls -la
         terraform init
-        terraform apply -auto-approve $(Build.SourcesDirectory)/azure-1/tfplan
+        terraform apply -auto-approve
         if [ $? -ne 0 ]; then
           echo "Error: Terraform apply failed. Please check the apply output for details."
           exit 1
