Update azure-pipelines-1.yml

diff --git a/azure-pipelines-1.yml b/azure-pipelines-1.yml
--- a/azure-pipelines-1.yml
+++ b/azure-pipelines-1.yml
@@ -8,72 +8,75 @@ pool:
   vmImage: 'ubuntu-latest'
 
 jobs:
-- job: terraform_approval
-  displayName: "Terraform Approval"
-  steps:
-    - script: 
-        echo "Terraform Approval Job"
-      displayName: 'Terraform Approval'
-      condition: succeededOrFailed()
+  - job: terraform_approval
+    displayName: "Terraform Approval"
+    steps:
+      - script: 
+          echo "Terraform Approval Job"
+        displayName: 'Terraform Approval'
+        condition: succeededOrFailed()
 
-- job: manual_approval
-  displayName: "Manual Approval"
-  dependsOn: terraform_approval
-  pool:
-    vmImage: 'ubuntu-latest'
-  steps:
-    - script: 
-        echo "Manual Approval Job"
-      displayName: 'Manual Approval'
-      condition: succeededOrFailed()
+  - job: manual_approval
+    displayName: "Manual Approval"
+    dependsOn: terraform_approval
+    pool:
+      vmImage: 'ubuntu-latest'
+    steps:
+      - script: 
+          echo "Manual Approval Job"
+        displayName: 'Manual Approval'
+        condition: succeededOrFailed()
 
-    - script: |
-        ls -la
-        pwd
-        cd $(Build.SourcesDirectory)/azure-1
-        pwd
-        terraform init
-      displayName: 'Terraform Init'
+      - script: |
+          ls -la
+          pwd
+          cd $(Build.SourcesDirectory)/azure-1
+          pwd
+          terraform init
+        displayName: 'Terraform Init'
 
-    - script: |
-        cd $(Build.SourcesDirectory)/azure-1
-        terraform validate
-      displayName: 'Terraform Validate'
+      - script: |
+          cd $(Build.SourcesDirectory)/azure-1
+          terraform validate
+        displayName: 'Terraform Validate'
 
-    - script: |
-        az login 
-    - script: |
-        cd $(Build.SourcesDirectory)/azure-1
-        terraform plan -out=tfplan
-        if [ $? -ne 0 ]; then
-          echo "Error: Terraform plan failed. Please check the plan output for details."
-          exit 1
-        fi
-      displayName: 'Terraform Plan'
+      - script: |
+          az login 
+        displayName: 'Azure Login'
 
-- job: manual_intervention
-  displayName: 'Manual Approval Intervention'
-  dependsOn: manual_approval
-  pool: server
-  steps:
-    - task: ManualValidation@0
-      timeoutInMinutes: 5
-      inputs:
-        instructions: 'Please review and manually approve the Terraform changes.'
+      - script: |
+          cd $(Build.SourcesDirectory)/azure-1
+          terraform plan -out=tfplan
+          if [ $? -ne 0 ]; then
+            echo "Error: Terraform plan failed. Please check the plan output for details."
+            exit 1
+          fi
+        displayName: 'Terraform Plan'
 
-- job: apply_changes
-  displayName: 'Apply Terraform Changes'
-  dependsOn: manual_intervention
-  pool:
-    vmImage: 'ubuntu-latest'
-  steps:
-    - script: |
-        az login
-        cd $(Build.SourcesDirectory)/azure-1
-        terraform init
-        terraform apply -auto-approve
-        if [ $? -ne 0 ]; then
-          echo "Error: Terraform apply failed. Please check the apply output for details."
-          exit 1
-        fi
-      displayName: 'Apply Terraform Changes'
+  - job: manual_intervention
+    displayName: 'Manual Approval Intervention'
+    dependsOn: manual_approval
+    pool: server
+    steps:
+      - task: ManualValidation@0
+        timeoutInMinutes: 5
+        inputs:
+          instructions: 'Please review and manually approve the Terraform changes.'
+
+  - job: apply_changes
+    displayName: 'Apply Terraform Changes'
+    dependsOn: manual_intervention
+    pool:
+      vmImage: 'ubuntu-latest'
+    steps:
+      - script: |
+          cd $(Build.SourcesDirectory)/azure-1
+          pwd
+          ls -la
+          terraform init
+          terraform apply -auto-approve
+          if [ $? -ne 0 ]; then
+            echo "Error: Terraform apply failed. Please check the apply output for details."
+            exit 1
+          fi
+        displayName: 'Apply Terraform Changes'
